name: Run Data2 Python script

on:
  schedule:
    - cron: '1 */6 * * *'  # runs at the first minute of every 6th hour. (12:01a, 6:01a, 12:01p, and 6:01p)
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run Python script
        env:
          SIURL: ${{ secrets.SIURL }}
        run: python data2.py

      - name: Check if data2.json exists and is non-empty
        run: |
          if [ ! -s data/data2.json ]; then
            echo "[]" > data/data2.json
          fi

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/data2.json || git commit -m "Create data2.json"
          git commit -m "Update data2.json" || echo "No changes to commit"
          git pull origin main || echo "No remote changes to pull"
          git push origin main
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
