name: Fetch Latest Articles

on:
  schedule:
    - cron: '0 6 * * *'    # Run at 11:30 AM IST (06:00 AM UTC)
    - cron: '0 9 * * *'    # Run at 02:30 PM IST (09:00 AM UTC)
    - cron: '0 12 * * *'   # Run at 05:30 PM IST (12:00 PM UTC)
    - cron: '0 15 * * *'   # Run at 08:30 PM IST (03:00 PM UTC)
    - cron: '30 17 * * *'  # Run at 11:00 PM IST (05:30 PM UTC)

jobs:
  fetch_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run script
        run: python data.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated logs" --allow-empty)
          git push
