name: Fetch Latest Articles

on:
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  fetch_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run script
        run: python data.py

      - name: Commit output JSON file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/latest_articles.json
          git commit -m "Update latest_articles.json" || echo "No changes to commit"
          git push
