name: Fetch Latest Articles

on:
  schedule:
    # Run daily at specific times
    - cron: '40 11 * * *'  # 11:40 AM
    - cron: '6 14 * * *'   # 2:06 PM
    - cron: '9 17 * * *'   # 5:09 PM
    - cron: '10 20 * * *'  # 8:10 PM
    - cron: '20 22 * * *'  # 10:20 PM

jobs:
  fetch_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run script
        env:
          geturlid: ${{ secrets.geturlid }}
        run: python data.py
