name: Fetch Latest Articles

on:
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  fetch_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Update to use Node.js 20
        with:
          ref: v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          node-version: '20'  # Specify Node.js 20

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run script
        env:
          geturlid: ${{ secrets.geturlid }}
        run: python data.py
