name: Run Python script

on:
  schedule:
    - cron: '30 6,9,12,15,18,21 * * *'  # Runs at 11:30 AM, 2:30 PM, 5:30 PM, 8:30 PM, and 11:00 PM (Indian Time)
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run Python script
        run: python data.py
      
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add /data/latest_articles.json || git add -A
          git commit -m "Update latest_articles.json" || echo "No changes to commit"
          git pull origin main || echo "No remote changes to pull"
          git push origin main
